sylius_ui:
    events:
        sylius.admin.dashboard.content:
            blocks:
                before_header_legacy:
                    enabled: false
                after_header_legacy:
                    enabled: false
                statistics:
                    enabled: false
                after_statistics_legacy:
                    enabled: false
                menu:
                    enabled: false
                after_menu_legacy:
                    enabled: false
                latest:
                    enabled: false
                after_content_legacy:
                    enabled: false

        sylius.shop.layout.header.grid:
            blocks:
                cart:
                    enabled: false
        
        sylius.shop.layout.header:
            blocks:
                menu:
                    enabled: false

        sylius.shop.homepage:
            blocks:
                latest_products:
                    enabled: false
                latest_products_carousel:
                    enabled: false
                products_grid:
                    enabled: false

        sylius.admin.customer.show.content:
            blocks:
                statistics:
                    enabled: false

        sylius.admin.customer.show.address:
            blocks:
                header:
                    enabled: false
                content:
                    enabled: false

        sylius.admin.layout.topbar_left:
            blocks:
                search:
                    enabled: false
